### ISSUE TITLE
[Paper 1.21.7] Legacy PlayerLoginEvent warning detected

### ISSUE THREAD

**Issue by x9nico** [SkinsRestorer/SkinsRestorerX#1980]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using forge/fabric/any modloader?

No

### Installed conforming to our guide?

- [x] I have read the installation guide and performed all steps

### Describe your issue

After tests with PR #1979 , when I'm joining my Paper 1.21.7 with SR plugin on it, I have this warning:

![Image](https://github.com/user-attachments/assets/f438f008-c2bf-4a85-8d06-d305a5a86a0b)

### How can we reproduce what you got?

1. Create 1.21.7 Paper Server
2. Upload SR into your plugins folder
3. Join your Server
4. See logs

### Minecraft implementation

```markdown
- Proxy: N/A
- Backend: This server is running Paper version 1.21.7-8-main@6e021c8 (2025-06-30T18:06:02Z) (Implementing API version 1.21.7-R0.1-SNAPSHOT)
You are running the latest version
```

### What client are you using?

Vanilla Launcher

### SkinsRestorer Version

15.7.4-SNAPSHOT

### List of plugins

[20:49:48 INFO]: ℹ Server Plugins (12): [20:49:48 INFO]: Paper Plugins (1): [20:49:48 INFO]:  - PvPBox [20:49:48 INFO]: Bukkit Plugins (11): [20:49:48 INFO]:  - AuthMe, ClearLag, FastAsyncWorldEdit, OldCombatMechanics, PlaceholderAPI, ProtocolLib, SkinsRestorer, ViaBackwards, ViaRewind, ViaVersion [20:49:48 INFO]:  WorldGuard

### Java Version

java version "21.0.2" 2024-01-16 LTS Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58) Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment]
Any update on this with the latest release?

**Comment by x9nico** [comment]
> Any update on this with the latest release?

On my side, I still have the warning into my logs:

<img width="1102" height="65" alt="Image" src="https://github.com/user-attachments/assets/f3ed677c-e2e6-4054-a96f-1a4a74d96ab5" />

**Comment by xknat** [comment]
should be fixed with latest skinsrestorer

**Comment by x9nico** [comment]
> should be fixed with latest skinsrestorer

I tried with latest version (15.8.0) with Paper 1.21.8 (build 60), I still have the warning 

<img width="1092" height="42" alt="Image" src="https://github.com/user-attachments/assets/8444a8b8-3735-44a9-9c49-bade8a8bbc97" />
